theme: jekyll-theme-tactile

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is
# unless you have other Jekyll builds using this same port that might
# cause conflicts. in that case, use another port such as 2001.
port: 4444



