


update:
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata01-1.krn -O sonata01-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata01-2.krn -O sonata01-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata01-3.krn -O sonata01-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata02-1.krn -O sonata02-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata02-2.krn -O sonata02-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata02-3.krn -O sonata02-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata03-1.krn -O sonata03-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata03-2.krn -O sonata03-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata03-3.krn -O sonata03-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata04-1.krn -O sonata04-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata04-2.krn -O sonata04-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata04-3.krn -O sonata04-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata05-1.krn -O sonata05-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata05-2.krn -O sonata05-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata05-3.krn -O sonata05-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-1.krn -O sonata06-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-2.krn -O sonata06-2.krn

	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3a.krn -O sonata06-3a.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3b.krn -O sonata06-3b.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3c.krn -O sonata06-3c.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3d.krn -O sonata06-3d.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3e.krn -O sonata06-3e.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3f.krn -O sonata06-3f.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3g.krn -O sonata06-3g.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3h.krn -O sonata06-3h.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3i.krn -O sonata06-3i.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3j.krn -O sonata06-3j.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3k.krn -O sonata06-3k.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3l.krn -O sonata06-3l.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata06-3m.krn -O sonata06-3m.krn

	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata07-1.krn -O sonata07-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata07-2.krn -O sonata07-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata07-3.krn -O sonata07-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata08-1.krn -O sonata08-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata08-2.krn -O sonata08-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata08-3.krn -O sonata08-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata09-1.krn -O sonata09-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata09-2.krn -O sonata09-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata09-3.krn -O sonata09-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata10-1.krn -O sonata10-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata10-2.krn -O sonata10-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata10-3.krn -O sonata10-3.krn

	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1a.krn -O sonata11-1a.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1b.krn -O sonata11-1b.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1c.krn -O sonata11-1c.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1d.krn -O sonata11-1d.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1e.krn -O sonata11-1e.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1f.krn -O sonata11-1f.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-1g.krn -O sonata11-1g.krn

	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-2.krn -O sonata11-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata11-3.krn -O sonata11-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata12-1.krn -O sonata12-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata12-2.krn -O sonata12-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata12-3.krn -O sonata12-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata13-1.krn -O sonata13-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata13-2.krn -O sonata13-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata13-3.krn -O sonata13-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata14-1.krn -O sonata14-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata14-2.krn -O sonata14-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata14-3.krn -O sonata14-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata15-1.krn -O sonata15-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata15-2.krn -O sonata15-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata15-3.krn -O sonata15-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata16-1.krn -O sonata16-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata16-2.krn -O sonata16-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata16-3.krn -O sonata16-3.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata17-1.krn -O sonata17-1.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata17-2.krn -O sonata17-2.krn
	wget https://raw.githubusercontent.com/craigsapp/mozart-piano-sonatas/master/kern/sonata17-3.krn -O sonata17-3.krn




